server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.205.11:2181

#eureka:
#  client:
#    register-with-eureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
#      # http://localhost:7001/eureka
#  #主机别名
#  instance:
#    instance-id: order80
#    prefer-ip-address: true


